# Socket.io server
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY server.js ./
COPY users.json ./
COPY gameState.json ./

EXPOSE 3001
ENV PORT=3001

CMD ["node", "server.js"]
